### ISSUE TITLE
🐛 remove cluster and account from resources

### ISSUE THREAD

**Issue by nxtcoder17** [kloudlite/api#157]
### Describe the Bug
we have `accountName` and `clusterName` in almost all of our resources. We initially did it to save a query to DB. But now, we want to keep the resources even if the user is deleting the cluster, and in that case all the resources would be stale, and will contain invalid `clusterName` reference (as it has already been deleted). 

We will introduce `projectId` in those resources, and in case of cluster deletion, we will mark project as stale, and things will be good.

Thanks!

**Comment by nxtCoder19** [comment]
Closing this issue as it has been already implemented.
