### ISSUE TITLE
🐛 Remove invited user from account is not working 

### ISSUE THREAD

**Issue by nxtCoder19** [kloudlite/api#235]
### Describe the Bug
 when user invite user for their account and then try to remove the same user, user got error like below:

<img width="1470" alt="Screenshot 2024-01-25 at 5 00 42 PM" src="https://github.com/kloudlite/api/assets/52462496/dd0d0164-b08f-4f74-94cd-de372f1e5973">

### To Reproduce
1. go to settings => user management => invite user => type user email => send invite
2. Go to pending invitations => more options => remove => remove user

### Expected Behavior
user should removed from pending invitation

### Current behaviour
getting api call error which is shown in above ss.

### More Information
...

### References, if any ?
...

Thanks!

**Comment by nxtcoder17** [comment]
already fixed now
