### ISSUE TITLE
🐛 For a new user sign up verify email is not working 

### ISSUE THREAD

**Issue by nxtCoder19** [kloudlite/api#238]
### Describe the Bug
When user signup and after proceed with verify email. user is still not able to login and getting error like:
 ```auth login user email not verified```

### Reference

<img width="1470" alt="Screenshot 2024-01-26 at 1 09 33 PM" src="https://github.com/kloudlite/api/assets/52462496/f987827f-2c5a-473c-abba-e44ecd527f57">

Thanks!

**Comment by nxtcoder17** [comment]
fixed now
